name: AirPrint
version: "2.0.0"
slug: airprint
description: AirPrint bridge for network printers that do not support it
url: https://github.com/aaronfagan/ha-airprint
arch:
  - amd64
init: true
boot: auto
startup: services
host_network: true
map:
  - addon_config:rw
options:
  printers:
    - name: Canon MF4890DW
      address: ""
      location: Office
      emoji: 🖨️
schema:
  printers:
    - name: str
      address: str?
      location: str?
      emoji: list(🖨️|🖨|📠|📄|🏢|🏠|none)?
