name: AirPrint
version: "1.4.0"
slug: airprint
description: AirPrint bridge for network printers that do not support it
url: https://github.com/aaronfagan/ha-airprint
arch:
  - amd64
init: true
boot: auto
startup: services
host_network: true
map:
  - addon_config:rw
options:
  printer_name: Canon MF4890DW
  printer_uri: socket://192.168.1.14:9100
  printer_location: Office
  printer_icon: ""
schema:
  printer_name: str
  printer_uri: str
  printer_location: str
  printer_icon: str?
